*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: ZCRMOSLAESCALVW.................................*
TABLES: ZCRMOSLAESCALVW, *ZCRMOSLAESCALVW. "view work areas
CONTROLS: TCTRL_ZCRMOSLAESCALVW
TYPE TABLEVIEW USING SCREEN '0031'.
DATA: BEGIN OF STATUS_ZCRMOSLAESCALVW. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZCRMOSLAESCALVW.
* Table for entries selected to show on screen
DATA: BEGIN OF ZCRMOSLAESCALVW_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZCRMOSLAESCALVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCRMOSLAESCALVW_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZCRMOSLAESCALVW_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZCRMOSLAESCALVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCRMOSLAESCALVW_TOTAL.

*...processing: ZSLPMCUSTPRODVW.................................*
TABLES: ZSLPMCUSTPRODVW, *ZSLPMCUSTPRODVW. "view work areas
CONTROLS: TCTRL_ZSLPMCUSTPRODVW
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_ZSLPMCUSTPRODVW. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZSLPMCUSTPRODVW.
* Table for entries selected to show on screen
DATA: BEGIN OF ZSLPMCUSTPRODVW_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZSLPMCUSTPRODVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSLPMCUSTPRODVW_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZSLPMCUSTPRODVW_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZSLPMCUSTPRODVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSLPMCUSTPRODVW_TOTAL.

*...processing: ZSLPMCUSTSYSTVW.................................*
TABLES: ZSLPMCUSTSYSTVW, *ZSLPMCUSTSYSTVW. "view work areas
CONTROLS: TCTRL_ZSLPMCUSTSYSTVW
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_ZSLPMCUSTSYSTVW. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZSLPMCUSTSYSTVW.
* Table for entries selected to show on screen
DATA: BEGIN OF ZSLPMCUSTSYSTVW_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZSLPMCUSTSYSTVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSLPMCUSTSYSTVW_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZSLPMCUSTSYSTVW_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZSLPMCUSTSYSTVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSLPMCUSTSYSTVW_TOTAL.

*...processing: ZSLPMEMAILRULEVW................................*
TABLES: ZSLPMEMAILRULEVW, *ZSLPMEMAILRULEVW. "view work areas
CONTROLS: TCTRL_ZSLPMEMAILRULEVW
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_ZSLPMEMAILRULEVW. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZSLPMEMAILRULEVW.
* Table for entries selected to show on screen
DATA: BEGIN OF ZSLPMEMAILRULEVW_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZSLPMEMAILRULEVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSLPMEMAILRULEVW_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZSLPMEMAILRULEVW_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZSLPMEMAILRULEVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSLPMEMAILRULEVW_TOTAL.

*...processing: ZSLPMPRFLDTRSVW.................................*
TABLES: ZSLPMPRFLDTRSVW, *ZSLPMPRFLDTRSVW. "view work areas
CONTROLS: TCTRL_ZSLPMPRFLDTRSVW
TYPE TABLEVIEW USING SCREEN '0070'.
DATA: BEGIN OF STATUS_ZSLPMPRFLDTRSVW. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZSLPMPRFLDTRSVW.
* Table for entries selected to show on screen
DATA: BEGIN OF ZSLPMPRFLDTRSVW_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZSLPMPRFLDTRSVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSLPMPRFLDTRSVW_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZSLPMPRFLDTRSVW_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZSLPMPRFLDTRSVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSLPMPRFLDTRSVW_TOTAL.

*...processing: ZSLPMPRODATTRVW.................................*
TABLES: ZSLPMPRODATTRVW, *ZSLPMPRODATTRVW. "view work areas
CONTROLS: TCTRL_ZSLPMPRODATTRVW
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_ZSLPMPRODATTRVW. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZSLPMPRODATTRVW.
* Table for entries selected to show on screen
DATA: BEGIN OF ZSLPMPRODATTRVW_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZSLPMPRODATTRVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSLPMPRODATTRVW_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZSLPMPRODATTRVW_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZSLPMPRODATTRVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSLPMPRODATTRVW_TOTAL.

*...processing: ZSLPMSETUPVW....................................*
TABLES: ZSLPMSETUPVW, *ZSLPMSETUPVW. "view work areas
CONTROLS: TCTRL_ZSLPMSETUPVW
TYPE TABLEVIEW USING SCREEN '0004'.
DATA: BEGIN OF STATUS_ZSLPMSETUPVW. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZSLPMSETUPVW.
* Table for entries selected to show on screen
DATA: BEGIN OF ZSLPMSETUPVW_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZSLPMSETUPVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSLPMSETUPVW_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZSLPMSETUPVW_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZSLPMSETUPVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSLPMSETUPVW_TOTAL.

*...processing: ZSLPMSTATEMAILVW................................*
TABLES: ZSLPMSTATEMAILVW, *ZSLPMSTATEMAILVW. "view work areas
CONTROLS: TCTRL_ZSLPMSTATEMAILVW
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_ZSLPMSTATEMAILVW. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZSLPMSTATEMAILVW.
* Table for entries selected to show on screen
DATA: BEGIN OF ZSLPMSTATEMAILVW_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZSLPMSTATEMAILVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSLPMSTATEMAILVW_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZSLPMSTATEMAILVW_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZSLPMSTATEMAILVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSLPMSTATEMAILVW_TOTAL.

*...processing: ZSLPMSTATFLOWVW.................................*
TABLES: ZSLPMSTATFLOWVW, *ZSLPMSTATFLOWVW. "view work areas
CONTROLS: TCTRL_ZSLPMSTATFLOWVW
TYPE TABLEVIEW USING SCREEN '0006'.
DATA: BEGIN OF STATUS_ZSLPMSTATFLOWVW. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZSLPMSTATFLOWVW.
* Table for entries selected to show on screen
DATA: BEGIN OF ZSLPMSTATFLOWVW_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZSLPMSTATFLOWVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSLPMSTATFLOWVW_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZSLPMSTATFLOWVW_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZSLPMSTATFLOWVW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSLPMSTATFLOWVW_TOTAL.

*.........table declarations:.................................*
TABLES: ZCRMO_SLA_ESCAL                .
TABLES: ZSLPM_CUST_PROD                .
TABLES: ZSLPM_CUST_SYST                .
TABLES: ZSLPM_EMAIL_RULE               .
TABLES: ZSLPM_PROD_ATTR                .
TABLES: ZSLPM_PR_FLD_TRS               .
TABLES: ZSLPM_SETUP                    .
TABLES: ZSLPM_STAT_EMAIL               .
TABLES: ZSLPM_STAT_FLOW                .
